version: "3.9"

services:
    db:
        image: postgres:12-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=lishobu
        networks:
            - server_side
        ports:
            - 15432:5432
        volumes:
            - db_data:/var/lib/postgresql/data
    backend:
        build:
            context: backend
            target: development
        env_file:
            - ./backend/.env
        networks:
            - client_side
            - server_side
        ports:
            - 8080:8080
        volumes:
            - ./backend/src:/app/src
            - backend_cache:/app/target
            - frontend_cache:/app/dist
        depends_on:
            - db
    frontend:
        build:
            context: frontend
            target: development
        env_file:
            - ./frontend/.env
        networks:
            - client_side
        ports:
            - 3000:3000
        volumes:
            - ./frontend/src:/app/src
            - frontend_cache:/app/dist
        depends_on:
            - backend

volumes:
    frontend_cache:
    backend_cache:
    db_data:

networks:
    client_side:
    server_side:

