version: "3.9"

services:
    db:
        image: postgres:12-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=lishobu
        networks:
            - server_side
        ports:
            - 15432:5432
        volumes:
            - db_data:/var/lib/postgresql/data
    backend:
        build:
            context: backend
            target: development
        environment:
            - SERVER_ADDR=0.0.0.0:8080
            - RUST_LOG=debug
            - PG_CONN=postgres://postgres:postgres@db:5432/lishobu
        networks:
            - client_side
            - server_side
        ports:
            - 18080:8080
        volumes:
            - ./backend/src:/app/src
            - backend_cache:/app/target
        depends_on:
            - db

volumes:
    backend_cache:
    db_data:

networks:
    client_side:
    server_side:

